[package]
name = "quizcrawler"
version = "0.1.0"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
toml = "*"
onig = "*"
serde = "*"
serde_derive = "*"
termion = "*"
structopt = "*"
clap = "*"